const defaults={A1:'Cecilia',A2:'Summer',A3:'Will',A4:'考赛尔',A5:'Lu Qian',E1:'Eric',B1:'Rhea',B2:'Nicole',B3:'Christina',B4:'Ruby',B5:'Saga',B6:'Leo',B7:'Frank',B8:'',C1:'Leeo',C2:'Qinrui Liu',C3:'Claire',C4:'Sylvia',C5:'Kaisen',C6:'Tycho',C7:'Eva',C8:'Bubble',D1:'Weijie Liu',D2:'空位',D3:'Sophie',D4:'空位',D5:'Wendy',D6:'空位',D7:'Fiona',D8:'空位',F1:'Cathy',F2:'Tracy'};
const people=window.ORG_PEOPLE;
const normalizePersonName=value=>(value||'').trim().toLowerCase();
const personIndex=new Map();Object.entries(people).forEach(([key,person])=>{person.key=key;const aliases=[key,person.english,person.english?.split(' ')[0],person.chinese,...(person.aliases||[])];aliases.filter(Boolean).forEach(alias=>personIndex.set(normalizePersonName(alias),person))});
const getPerson=name=>personIndex.get(normalizePersonName(name));
const storageVersion='5';let savedSeats=JSON.parse(localStorage.getItem('officeSeats')||'{}');if(localStorage.getItem('officeSeatsVersion')!==storageVersion){savedSeats={};localStorage.removeItem('officeSeats');localStorage.setItem('officeSeatsVersion',storageVersion)}Object.keys(savedSeats).forEach(id=>{if(savedSeats[id]==='考塞尔')savedSeats[id]='考赛尔'});let seats={...defaults,...savedSeats},editing=false,editId=null,selectedId=null;const NS='http://www.w3.org/2000/svg',root=document.querySelector('#workstations'),financeRoot=document.querySelector('#financeSeats');
const slots=[['A1',420,246,'top'],['A2',540,246,'top'],['A3',300,316,'bottom'],['A4',420,316,'bottom'],['A5',540,316,'bottom'],['B1',195,400,'top'],['B2',310,400,'top'],['B3',425,400,'top'],['B4',540,400,'top'],['B5',195,470,'bottom'],['B6',310,470,'bottom'],['B7',425,470,'bottom'],['C1',195,550,'top'],['C2',310,550,'top'],['C3',425,550,'top'],['C4',540,550,'top'],['C5',195,620,'bottom'],['C6',310,620,'bottom'],['C7',425,620,'bottom'],['C8',540,620,'bottom'],['D1',195,700,'top'],['D2',310,700,'top'],['D3',425,700,'top'],['D4',540,700,'top'],['D5',195,770,'bottom'],['D6',310,770,'bottom'],['D7',425,770,'bottom'],['D8',540,770,'bottom']];
const seatIds=[...slots.map(([id])=>id),'E1','F1','F2'];
function isVacant(value){return !value||value==='空位'}
function displaySeatName(value){if(isVacant(value))return I18N.t('vacant');const info=getPerson(value);if(!info)return value;if(info.key==='考赛尔')return '考赛尔';return I18N.getLanguage()==='zh'?(info.chinese||info.key):info.key}
function updateStats(){const total=seatIds.length,used=seatIds.filter(id=>!isVacant(seats[id])).length;document.querySelector('#totalSeats').textContent=total;document.querySelector('#usedSeats').textContent=used;document.querySelector('#vacantSeats').textContent=total-used}
function node(tag,a={},text=''){const n=document.createElementNS(NS,tag);Object.entries(a).forEach(([k,v])=>{if(v!=='')n.setAttribute(k,v)});if(text)n.textContent=text;return n}
function render(){root.innerHTML='';slots.forEach(([id,x,y,side])=>{const value=seats[id]||'',vacant=isVacant(value),g=node('g',{'data-seat':id,class:`seat ${vacant?'vacant':''}`,tabindex:'0',role:'button'}),deskTransform=side==='top'?`rotate(180 ${x+46} ${y+34})`:'',nameY=side==='top'?y+54:y+18;g.append(node('rect',{class:'hit',x:x-3,y:y-4,width:98,height:76,rx:7}),node('image',{class:'desk-img',href:'assets/images/desk.png',x,y,width:92,height:68,transform:deskTransform}));if(value){if(!vacant)g.append(node('circle',{class:'seat-dot',cx:x+7,cy:nameY-9,r:3}));g.append(node('text',{class:'seat-name',x:x+46,y:nameY},displaySeatName(value)))}g.addEventListener('click',()=>handle(id));g.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handle(id)}});root.append(g)});renderFinance();document.querySelector('#ericName').textContent=displaySeatName('Eric');updateStats()}
function renderFinance(){financeRoot.innerHTML='';[{id:'F1',x:758,angle:90,labelX:778},{id:'F2',x:826,angle:-90,labelX:856}].forEach(({id,x,angle,labelX})=>{const g=node('g',{'data-seat':id,class:'seat finance-seat',tabindex:'0',role:'button'}),cx=x+28,cy=1031;g.append(node('rect',{class:'hit',x:x-4,y:998,width:62,height:68,rx:6}),node('image',{class:'desk-img',href:'assets/images/desk.png',x,y:1009,width:56,height:44,transform:`rotate(${angle} ${cx} ${cy})`}),node('circle',{class:'seat-dot',cx:labelX-25,cy:1067,r:3}),node('text',{class:'seat-name',x:labelX,y:1069},displaySeatName(seats[id])));g.addEventListener('click',()=>handle(id));financeRoot.append(g)})}
function localizedSeatMeta(id){if(id==='E1')return `E1 · ${I18N.t('ceoSeat')}`;if(id.startsWith('F'))return `${id} · ${I18N.t('financeSeat')}`;return I18N.getLanguage()==='zh'?`${id} · ${id[0]} ${I18N.t('zone')}`:`${id} · ${I18N.t('zone')} ${id[0]}`}
function updateEditButton(){document.querySelector('#edit').textContent=I18N.t(editing?'doneEditing':'editSeats')}
function resetDetails(){selectedId=null;document.querySelector('#person').textContent=I18N.t('selectSeat');document.querySelector('#alternateName').textContent=I18N.t('detailsHint');document.querySelector('#personDetails').hidden=true;document.querySelector('#clear').disabled=true}
function handle(id){if(editing){editId=id;document.querySelector('#seatId').textContent=`${id} ${I18N.t('seatSuffix')}`;document.querySelector('#name').value=isVacant(seats[id])?'':seats[id];document.querySelector('#dialog').showModal();return}showDetails(id)}
function showDetails(id){selectedId=id;document.querySelectorAll('.seat').forEach(g=>g.classList.toggle('active',g.dataset.seat===id));const display=seats[id]||'',info=getPerson(display),details=document.querySelector('#personDetails');document.querySelector('#clear').disabled=false;if(isVacant(display)){document.querySelector('#person').textContent=I18N.t('vacant');document.querySelector('#alternateName').textContent=I18N.t('unassigned');details.hidden=true;return}document.querySelector('#person').textContent=displaySeatName(display);let alternate='';if(info&&info.key!=='考赛尔')alternate=I18N.getLanguage()==='zh'?(info.english||''):(info.chinese||'');document.querySelector('#alternateName').textContent=alternate||I18N.t('notProvided');const englishFull=document.querySelector('#englishFull'),department=document.querySelector('#department');englishFull.textContent=info?(info.english||''):display;englishFull.parentElement.hidden=!englishFull.textContent;department.textContent=info?I18N.localizeDepartment(info.department):I18N.t('notProvided');department.parentElement.hidden=!department.textContent;document.querySelector('#title').textContent=info?I18N.localizeTitle(info.title):I18N.t('notProvided');document.querySelector('#meta').textContent=localizedSeatMeta(id);details.hidden=false}
document.querySelector('#search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.seat').forEach(g=>g.classList.remove('search-hit'));if(!q)return;Object.entries(seats).filter(([,display])=>{const info=getPerson(display);return [display,info?.key,info?.english,info?.chinese].some(value=>value&&value.toLowerCase().includes(q))}).forEach(([id])=>document.querySelector(`[data-seat="${id}"]`)?.classList.add('search-hit'))});
document.querySelector('#edit').addEventListener('click',()=>{editing=!editing;document.querySelector('#map').classList.toggle('editing',editing);updateEditButton()});
document.querySelector('#form').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();seats[editId]=document.querySelector('#name').value.trim()||'空位';localStorage.setItem('officeSeats',JSON.stringify(seats));document.querySelector('#dialog').close();render();showDetails(editId)});
document.querySelector('#clear').addEventListener('click',()=>{document.querySelectorAll('.seat').forEach(g=>g.classList.remove('active','search-hit'));resetDetails()});
document.querySelector('#export').addEventListener('click',()=>{const b=new Blob([JSON.stringify(seats,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='seats.json';a.click();URL.revokeObjectURL(u)});
window.addEventListener('languagechange',()=>{render();updateEditButton();if(selectedId)showDetails(selectedId);else resetDetails()});
const ericSeat=document.querySelector('#ericSeat');ericSeat.addEventListener('click',()=>handle('E1'));ericSeat.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handle('E1')}});
const ma=document.querySelector('#meetingA');for(let i=0;i<4;i++){ma.append(node('image',{href:'assets/images/armchair.png',x:660,y:43+i*24,width:26,height:26,transform:`rotate(-90 673 ${56+i*24})`}),node('image',{href:'assets/images/armchair.png',x:782,y:43+i*24,width:26,height:26,transform:`rotate(90 795 ${56+i*24})`}))}
const plantPositions=[[137,620],[137,665],[137,710],[137,755],[137,810],[137,855],[180,855],[223,855],[266,855],[309,855],[137,902],[180,902],[223,902],[266,902],[309,902],[137,950],[180,950],[223,950],[266,950],[309,950],[352,950],[124,1003],[169,1003],[214,1003],[259,1003],[304,1003],[349,1003],[394,1003],[439,1003],[484,1003],[529,1003],[574,1003],[619,1003],[124,1046],[169,1046],[214,1046],[259,1046],[304,1046],[349,1046],[394,1046],[439,1046],[484,1046],[529,1046],[574,1046],[619,1046]];const plantRoot=document.querySelector('#plants');plantPositions.forEach(([x,y])=>plantRoot.append(node('image',{href:'assets/images/plant.png',x,y,width:36,height:36})));render();resetDetails();updateEditButton();
