const downloadBlob=(blob,fileName)=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const blobToDataUrl=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});
async function serializedMap(){const source=document.querySelector('#map'),clone=source.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width','900');clone.setAttribute('height','1100');clone.querySelectorAll('.active,.search-hit').forEach(el=>el.classList.remove('active','search-hit'));const css=await fetch('styles.css').then(response=>response.text());const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent=css;clone.prepend(style);await Promise.all([...clone.querySelectorAll('image')].map(async image=>{const href=image.getAttribute('href');if(!href||href.startsWith('data:'))return;const blob=await fetch(new URL(href,document.baseURI)).then(response=>response.blob());image.setAttribute('href',await blobToDataUrl(blob))}));return new XMLSerializer().serializeToString(clone)}
async function mapCanvas(){const svg=await serializedMap(),blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url});const canvas=document.createElement('canvas');canvas.width=1800;canvas.height=2200;const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);return canvas}
const canvasBlob=(canvas,type,quality)=>new Promise(resolve=>canvas.toBlob(resolve,type,quality));
const encode=text=>new TextEncoder().encode(text);const joinBytes=parts=>{const length=parts.reduce((sum,part)=>sum+part.length,0),result=new Uint8Array(length);let offset=0;parts.forEach(part=>{result.set(part,offset);offset+=part.length});return result};
function pdfFromJpeg(jpeg,width,height){const pageW=595,pageH=842,margin=24,scale=Math.min((pageW-margin*2)/width,(pageH-margin*2)/height),drawW=width*scale,drawH=height*scale,x=(pageW-drawW)/2,y=(pageH-drawH)/2,stream=`q\n${drawW.toFixed(2)} 0 0 ${drawH.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm\n/Im0 Do\nQ\n`,objects=[encode('<< /Type /Catalog /Pages 2 0 R >>'),encode('<< /Type /Pages /Kids [3 0 R] /Count 1 >>'),encode('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 5 0 R >> >> /Contents 4 0 R >>'),joinBytes([encode(`<< /Length ${encode(stream).length} >>\nstream\n`),encode(stream),encode('endstream')]),joinBytes([encode(`<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,encode('\nendstream')])],header=encode('%PDF-1.4\n'),parts=[header],offsets=[0];let offset=header.length;objects.forEach((body,index)=>{offsets.push(offset);const object=joinBytes([encode(`${index+1} 0 obj\n`),body,encode('\nendobj\n')]);parts.push(object);offset+=object.length});const xrefOffset=offset,xref=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(value=>String(value).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;parts.push(encode(xref));return new Blob([joinBytes(parts)],{type:'application/pdf'})}
async function withBusy(button,task){const label=button.textContent;button.disabled=true;button.textContent='生成中…';try{await task()}catch(error){console.error(error);alert('导出失败，请刷新页面后重试。')}finally{button.disabled=false;button.textContent=label}}
document.querySelector('#exportPng').addEventListener('click',event=>withBusy(event.currentTarget,async()=>{const canvas=await mapCanvas(),blob=await canvasBlob(canvas,'image/png');downloadBlob(blob,'office-seating-map.png')}));
document.querySelector('#exportPdf').addEventListener('click',event=>withBusy(event.currentTarget,async()=>{const canvas=await mapCanvas(),data=canvas.toDataURL('image/jpeg',.92).split(',')[1],binary=atob(data),jpeg=Uint8Array.from(binary,char=>char.charCodeAt(0));downloadBlob(pdfFromJpeg(jpeg,canvas.width,canvas.height),'office-seating-map.pdf')}));
