const TRANSLATIONS={
 en:{eyebrow:'OFFICE DIRECTORY',pageTitle:'Office Seating Map',searchPlaceholder:'Search names…',editSeats:'Edit seats',doneEditing:'Done',exportJson:'Export JSON',exportPng:'Export PNG',exportPdf:'Export PDF',seatDistribution:'Seat Distribution',seatStats:'Seat statistics',totalSeats:'Total seats',usedSeats:'Used',availableSeats:'Available',occupied:'Occupied',vacant:'Vacant',mapAria:'Office seating floor plan',ceoOffice:'CEO Office',meetingA:'Meeting Room A',meetingB:'Meeting Room B',meetingC:'Meeting Room C',phoneBooth:'Phone Booth',entrance:'Entrance',pantry:'Pantry',breakRoom:'Break Room',financeRoom:'Finance',seatDetails:'SEAT DETAILS',selectSeat:'Select a seat',detailsHint:'Click a person on the map to view details.',englishName:'English name',department:'Department',jobTitle:'Job title',seat:'Seat',clearSelection:'Clear selection',editSeatEyebrow:'EDIT SEAT',editSeatName:'Edit seat name',name:'Name',cancel:'Cancel',save:'Save',unassigned:'This seat is currently unassigned.',notProvided:'Not provided in ORG-CHART',seatSuffix:'seat',ceoSeat:'CEO Office',financeSeat:'Finance',zone:'Zone',generating:'Generating…',exportError:'Export failed. Please refresh the page and try again.'},
 zh:{eyebrow:'办公室名录',pageTitle:'办公室工位图',searchPlaceholder:'搜索中英文姓名…',editSeats:'编辑工位',doneEditing:'完成编辑',exportJson:'导出 JSON',exportPng:'导出 PNG',exportPdf:'导出 PDF',seatDistribution:'工位分布',seatStats:'座位统计',totalSeats:'总座位',usedSeats:'已使用',availableSeats:'空余',occupied:'在座',vacant:'空位',mapAria:'办公室工位平面图',ceoOffice:'CEO 办公室',meetingA:'会议室 A',meetingB:'会议室 B',meetingC:'会议室 C',phoneBooth:'电话亭',entrance:'入口',pantry:'茶水间',breakRoom:'休息室',financeRoom:'财务室',seatDetails:'工位详情',selectSeat:'选择一个工位',detailsHint:'点击地图上的人员查看详细信息。',englishName:'英文名',department:'部门',jobTitle:'职务',seat:'工位',clearSelection:'清除选择',editSeatEyebrow:'编辑工位',editSeatName:'修改工位姓名',name:'姓名',cancel:'取消',save:'保存',unassigned:'此工位暂未安排人员',notProvided:'ORG-CHART 未提供',seatSuffix:'工位',ceoSeat:'CEO 办公室',financeSeat:'财务室',zone:'区',generating:'生成中…',exportError:'导出失败，请刷新页面后重试。'}
};
const DEPARTMENT_ZH={'CEO Office':'CEO办公室','国内HR':'国内HR','Global HR':'全球人力资源部','Solution & Delivery':'解决方案与交付部','Finance':'财务部','IT':'信息技术部','Global Strategic Accounts & Market Development':'全球战略客户与市场发展部','Business Operations':'业务运营部','Site Operations & Marketing':'站点运营与市场部','Legal':'法务部'};
const TITLE_ZH={'CEO':'首席执行官','CEO Assistant':'CEO助理','HR intern':'人力资源实习生','HR & Talent Acquisition Director':'人力资源与招聘总监','Senior Talent Acquisition Manager':'高级招聘经理','Global Talent Acquisition Manager':'全球招聘经理','Human Resource Manager':'人力资源经理','Global TA Operations Specialist':'全球招聘运营专员','Senior Human Resource Specialist':'高级人力资源专员','Senior Talent Acquisition Specialist':'高级招聘专员','HR & Payments Operations Specialist':'人力资源与薪酬运营专员','Human Resource Specialist':'人力资源专员','Solution & Delivery Director':'解决方案与交付总监','Senior Project Manager':'高级项目经理','Solution Architect':'解决方案架构师','Project Manager':'项目经理','Vendor Management Specialist':'供应商管理专员','Project Assistant':'项目助理','Finance Manager':'财务经理','Senior Accountant':'高级会计','Finance Analyst':'财务分析师','AP Specialist':'应付账款专员','Administrative Assistant':'行政助理','Senior IT Manager':'高级IT经理','IT Security & Operation Specialist':'IT安全与运维专员','IT Support Specialist':'IT支持专员','VP':'副总裁','Strategic Accounts Director':'战略客户总监','BD Assistant':'商务拓展助理','Business Operations Manager':'业务运营经理','Business Assistant':'业务助理','Site Operations & Marketing Director':'站点运营与市场总监','General Counsel':'总法律顾问','Legal Counsel':'法律顾问'};
let currentLanguage=localStorage.getItem('officeLanguage')||'en';if(!['en','zh'].includes(currentLanguage))currentLanguage='en';
const t=key=>TRANSLATIONS[currentLanguage][key]||key;
function applyStaticTranslations(){document.documentElement.lang=currentLanguage==='zh'?'zh-CN':'en';document.title=t('pageTitle');document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAriaLabel)));const toggle=document.querySelector('#languageToggle');if(toggle){toggle.textContent=currentLanguage==='en'?'Chinese':'英文';toggle.setAttribute('aria-label',currentLanguage==='en'?'Switch to Chinese':'切换到英文');const entrance=document.querySelector('#entranceLabel');if(entrance)entrance.setAttribute('x',currentLanguage==='en'?'817':'846')}}
function setLanguage(language){currentLanguage=language;localStorage.setItem('officeLanguage',language);applyStaticTranslations();window.dispatchEvent(new CustomEvent('languagechange',{detail:{language}}))}
function localizeDepartment(value){if(!value)return '';if(currentLanguage==='zh')return DEPARTMENT_ZH[value]||value;if(value==='国内HR')return 'Domestic HR';return value}
function localizeTitle(value){if(!value)return '';return currentLanguage==='zh'?(TITLE_ZH[value]||value):value}
window.I18N={t,getLanguage:()=>currentLanguage,setLanguage,applyStaticTranslations,localizeDepartment,localizeTitle};
applyStaticTranslations();document.querySelector('#languageToggle').addEventListener('click',()=>setLanguage(currentLanguage==='en'?'zh':'en'));
