window.ORG_PEOPLE={
  Eric:{english:'Eric Zhang',chinese:'张韬',department:'',title:'CEO'},
  Summer:{english:'Summer',chinese:'袁嘉美',department:'CEO Office',title:'CEO Assistant'},
  '考赛尔':{english:'',chinese:'考赛尔',department:'国内HR',title:'HR intern',aliases:['考塞尔']},
  Frank:{english:'Frank Guo',chinese:'郭子健',department:'Global HR',title:'HR & Talent Acquisition Director'},
  Kaisen:{english:'Kaisen Wan',chinese:'宛楷森',department:'Global HR',title:'Senior Talent Acquisition Manager'},
  Will:{english:'Will Tian',chinese:'田学维',department:'Global HR',title:'Global Talent Acquisition Manager'},
  Yanan:{english:'Yanan Sun',chinese:'孙亚男',department:'Global HR',title:'Human Resource Manager'},
  Cecilia:{english:'Cecilia Feng',chinese:'冯希雅',department:'Global HR',title:'Global TA Operations Specialist'},
  Bubble:{english:'Bubble Liu',chinese:'刘玥',department:'Global HR',title:'Senior Human Resource Specialist'},
  Tycho:{english:'Tycho Xu',chinese:'徐思鸣',department:'Global HR',title:'Senior Talent Acquisition Specialist'},
  Rhea:{english:'Rhea Feng',chinese:'冯川川',department:'Global HR',title:'HR & Payments Operations Specialist'},
  Sophie:{english:'Sophie Zang',chinese:'臧雨',department:'Global HR',title:'Human Resource Specialist'},
  Eva:{english:'Eva Niu',chinese:'牛丹盟',department:'Global HR',title:'Human Resource Specialist'},
  Clark:{english:'Clark Ji',chinese:'季伟男',department:'Solution & Delivery',title:'Solution & Delivery Director'},
  Fiona:{english:'Fiona Xue',chinese:'薛文秀',department:'Solution & Delivery',title:'Senior Project Manager'},
  Jimmy:{english:'Jimmy Sun',chinese:'孙鑫',department:'Solution & Delivery',title:'Senior Project Manager'},
  Lola:{english:'Lola Yu',chinese:'于海波',department:'Solution & Delivery',title:'Senior Project Manager'},
  Jay:{english:'Jay Huang',chinese:'黄武',department:'Solution & Delivery',title:'Solution Architect'},
  'Weijie Liu':{english:'Weijie Liu',chinese:'刘维杰',department:'Solution & Delivery',title:'Project Manager'},
  Joseph:{english:'Joseph Miao',chinese:'缪肖君',department:'Solution & Delivery',title:'Project Manager'},
  Noemi:{english:'Noemi Gao',chinese:'高沁怡',department:'Solution & Delivery',title:'Project Manager'},
  Delia:{english:'Delia Cai',chinese:'蔡雪莲',department:'Solution & Delivery',title:'Project Manager'},
  Reeta:{english:'Reeta Gao',chinese:'高俊涵',department:'Solution & Delivery',title:'Project Manager'},
  Ruby:{english:'Ruby Wang',chinese:'王茹萍',department:'Solution & Delivery',title:'Vendor Management Specialist'},
  Alex:{english:'Alex Li',chinese:'李舒宁',department:'Solution & Delivery',title:'Project Assistant'},
  Eleanor:{english:'Eleanor Ma',chinese:'马演菲',department:'Solution & Delivery',title:'Project Assistant'},
  Lexie:{english:'Lexie Wu',chinese:'吴思璇',department:'Solution & Delivery',title:'Project Assistant'},
  Ari:{english:'Ari Wang',chinese:'王蕾',department:'Solution & Delivery',title:'Project Assistant'},
  Claire:{english:'Claire Qu',chinese:'屈明明',department:'Finance',title:'Finance Manager'},
  Tracy:{english:'Tracy Jiang',chinese:'姜丽萍',department:'Finance',title:'Senior Accountant'},
  'Qinrui Liu':{english:'Qinrui Liu',chinese:'刘沁蕊',department:'Finance',title:'Finance Analyst'},
  Sylvia:{english:'Sylvia Fan',chinese:'樊思雨',department:'Finance',title:'Finance Analyst'},
  Nicole:{english:'Nicole Song',chinese:'宋秋璇',department:'Finance',title:'AP Specialist'},
  Cathy:{english:'Cathy Xu',chinese:'许佳莹',department:'Finance',title:'Administrative Assistant'},
  Saga:{english:'Saga Qin',chinese:'秦思佳',department:'IT',title:'Senior IT Manager'},
  Leo:{english:'Leo Zhang',chinese:'张博文',department:'IT',title:'IT Security & Operation Specialist'},
  Leeo:{english:'Leeo Lin',chinese:'林封相',department:'IT',title:'IT Support Specialist'},
  Zhanyan:{english:'Zhanyan Liu',chinese:'刘展颜',department:'Global Strategic Accounts & Market Development',title:'VP'},
  Sindy:{english:'Sindy Wen',chinese:'文哲',department:'Global Strategic Accounts & Market Development',title:'Strategic Accounts Director'},
  Wendy:{english:'Wendy Wu',chinese:'吴小容',department:'Global Strategic Accounts & Market Development',title:'BD Assistant'},
  'Lu Qian':{english:'Lu Qian',chinese:'钱露',department:'Business Operations',title:'Business Operations Manager'},
  Christina:{english:'Christina Yuan',chinese:'袁梦',department:'Business Operations',title:'Business Assistant'},
  Fatima:{english:'Fatima Guan',chinese:'关婧思',department:'Site Operations & Marketing',title:'Site Operations & Marketing Director'},
  Mona:{english:'Mona Guo',chinese:'ORG-CHART 未提供',department:'Legal',title:'General Counsel'},
  Irene:{english:'Irene Zhang',chinese:'张诗悦',department:'Legal',title:'Legal Counsel'}
};
